### ISSUE TITLE
crash on attempting to open a leather satchel

### ISSUE THREAD

**Issue by xigzagoon** [JeweyxD/Forge-Rosia-1.18.2#2]
with the latest TFC release (2.2.24) attempting to open a leather satchel (i.e. holding and attempting to use it) causes a crash. crash report is attached
[crash-2023-06-13_16.31.19-server.txt](https://github.com/JeweyxD/Forge-Rosia-1.18.2/files/11739756/crash-2023-06-13_16.31.19-server.txt)

**Comment by JeweyxD** [comment]
Fixed in the next release.
