### ISSUE TITLE
Client-side crash caused by the battery.

### ISSUE THREAD

**Issue by MEEPofFaith** [JeweyxD/Forge-Rosia-1.18.2#3]
Server does not crash, only client.
Could place the battery, the crashing only begins when you leave the area or leave the game, then attempt to reload those chunks by returning or joining the game.

[crash-2023-07-01_13.35.06-client.txt](https://github.com/JeweyxD/Forge-Rosia-1.18.2/files/11929842/crash-2023-07-01_13.35.06-client.txt)

**Comment by BowBoy1** [comment]
Encountered basically the same crash. Seems to only initially start when the battery is actively outputting power.
[crash-2023-09-23_11.33.14-client.txt](https://github.com/JeweyxD/Forge-Rosia-1.18.2/files/12706820/crash-2023-09-23_11.33.14-client.txt)
